SlnSistemaHospitalar/src/SistemaHospitalar.Web/Controllers/PacientesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaHospitalar.Domain.DTO;
using SistemaHospitalar.Domain.Entities;
using SistemaHospitalar.Domain.IServices;
using SistemaHospitalar.Web.Helper;
using SistemaHospitalar.Web.Models;

namespace SistemaHospitalar.Web.Controllers
{
    public class PacientesController : Controller
    {
        private readonly IPacienteService _service;
        private readonly IConvenioService _convenioService;
        private readonly IPessoaService _pessoaService;

        public PacientesController(IPacienteService service, IConvenioService convenioService, IPessoaService pessoaService)
        {
            _service = service;
            _convenioService = convenioService;
            _pessoaService = pessoaService;
        }


        // GET: PacientesController
        public async Task<ActionResult> Index()
        {
            var Paciente = await _service.GetAll();
            return View(Paciente);
        }

        // GET: PacientesController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _service.FindById(id);
            return View(paciente);
        }

        // GET: PacientesController/Create
        public async Task<ActionResult> Create()
        {
            ViewData["convenioId"] = new SelectList(await _convenioService.GetAll(), "id", "nome", "Selecione...");
            return View();
        }

        // POST: PacientesController/Create
        [HttpPost]

        public async Task<IActionResult> Create(PacienteDTO paciente)
        {
            var pessoas = await _pessoaService.GetAll();

            int count = 0;
            foreach (var item in pessoas)
            {
                count++;
                if (count == pessoas.Count)
                {
                    //ultima Pessoa
                    paciente.pessoaId = item.id;
                }
            }

            if (ModelState.IsValid)
            {
                    
                await _service.Save(paciente);
                TempData["MensagemSucesso"] = "Paciente adicionado com sucesso";
                return RedirectToAction(nameof(Index));
            }
                ViewData["convenioId"] = new SelectList(await _convenioService.GetAll(), "id", "nome", "Selecione...");
                return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Paciente = await _service.FindById(id);
            ViewData["convenioId"] = new SelectList(await _convenioService.GetAll(), "id", "nome", "Selecione...");
            return View(Paciente);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, PacienteDTO paciente)
        {
            if (id == null || paciente == null)
            {
                return NotFound();
            }

            //var pessoa = await _pessoaService.FindById(paciente.pessoa.id);
            //aciente.pessoaId = pessoa.id;
            if (ModelState.IsValid)
            {
                await _service.Save(paciente);
                TempData["MensagemSucesso"] = "Registro alterado com sucesso";
                return RedirectToAction(nameof(Index));
            }

            //ViewData["pessoaId"] = new SelectList(_pessoaService.GetAll(), "id", "nome", "Selecione...");
            ViewData["convenioId"] = new SelectList(await _convenioService.GetAll(), "id", "nome", "Selecione...");
            TempData["MensagemErro"] = "Erro ao alterar registro";
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJson
            {
                status = "Success",
                code = "200"
            };
            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJson
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJson
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Pacientes/Create.cshtml
@using SistemaHospitalar.Domain.Entities
@using SistemaHospitalar.Domain.Enum
@model SistemaHospitalar.Domain.DTO.PacienteDTO

@{
    ViewData["Title"] = "Criar";
}

<div class="text-center title-page">
    <h1 class="display-1 fw-bold text-success mt-5 mb-5"><strong>Adicionar Paciente</strong></h1>
</div>                      

<form asp-controller="Pacientes" asp-action="Create" method="post">
 <div class="container">
    <div class="row justify-content-center">
    <div class="col-3">
        <div class="form-group text-dark">
        <label autofocus asp-for="convenioId" for="convenioId" class="color-label">Nome do Convênio</label>
        <select asp-for="convenioId" class="form-control" asp-items="ViewBag.ConvenioId"></select>
        <span asp-validation-for="convenioId" class="text-danger"></span> 

        <div class="form-group mt-2 ">
            <label asp-for="situacao" class="control-label login-title"></label>
            <select asp-for="situacao" class="form-control">
                <option value="0">Selecione</option>
                <option value="@SituacaoEnum.Obito">Óbito</option>
                <option value="@SituacaoEnum.Alta">Alta</option>
                <option value="@SituacaoEnum.Ativo">Ativo</option>
            </select>
            <span asp-validation-for="situacao" class="text-danger"></span>
        </div>


    </div>
            <div class="form-group mt-3 d-flex">
                <a id="btn-pessoa" class="btn btn-warning btn-sm btn-block w-100 float-start" onclick="createPessoa()" data-bs-toggle="modal" data-bs-target="#formModal">Cadastrar Dados Pessoais</a>
                <input type="submit" value="Cadastrar" class="btn ms-2 btn-primary btn-block w-100 btn-sm float-end" />
            </div>
             <a class="btn btn-info btn-block w-100 mt-3" onclick="createEndereco()" data-bs-toggle="modal" data-bs-target="#formModal">Cadastrar Endereço</a>
            
         </div>
    

    </div>
 </div> 
                                   
</form>


<div class="mt-5">
    <a class="btn btn-dark" asp-action="Index">Voltar para Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>


        
    </script>
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Pacientes/Details.cshtml
@model SistemaHospitalar.Domain.DTO.PacienteDTO

@{
    ViewData["Title"] = "Details";
}

<h1 class="display-3 text-center mt-3">@Model.pessoa.nome @Model.pessoa.sobrenome</h1>

<div>
    <hr class="bg-light" />
    <dl class="row">
        <h4 class="text-success fw-bold mb-5 mt-5">Dados do Paciente</h4>
        <dt class="col-sm-3 menu-listagem">
            Código do Paciente
        </dt>
        <dd class="col-sm-10 text-dark menu-listagem">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-3 menu-listagem">
            @Html.DisplayNameFor(model => model.pessoa.id)
        </dt>
        <dd class="col-sm-10 text-dark menu-listagem">
            @Html.DisplayFor(model => model.pessoa.id)
        </dd>
        <dt class="col-sm-3 menu-listagem">
            @Html.DisplayNameFor(model => model.convenio.nome)
        </dt>
        <dd class="col-sm-10 text-dark menu-listagem">
            @Html.DisplayFor(model => model.convenio.nome)
        </dd>
        <dt class="col-sm-3 menu-listagem">
            @Html.DisplayNameFor(model => model.situacao)
        </dt>
        <dd class="col-sm-10 text-dark menu-listagem">
            @Html.DisplayFor(model => model.situacao)
        </dd>

        <h4 class="text-success fw-bold mb-5  mt-5">Dados Pessoais</h4>
        <div class="row">
            <div class="col">
                <dt class="col-sm-2 menu-listagem">
                    @Html.DisplayNameFor(model => model.pessoa.nome)
                </dt>
                <dd class="col-sm-10 text-dark menu-listagem">
                    @Html.DisplayFor(model => model.pessoa.nome)
                </dd>
                <dt class="col-sm-2 menu-listagem">
                    @Html.DisplayNameFor(model => model.pessoa.sobrenome)
                </dt>
                <dd class="col-sm-10 text-dark menu-listagem">
                    @Html.DisplayFor(model => model.pessoa.sobrenome)
                </dd>
                <dt class="col-sm-2 menu-listagem">
                    @Html.DisplayNameFor(model => model.pessoa.cpf)
                </dt>
                <dd class="col-sm-10 text-dark menu-listagem">
                    @Html.DisplayFor(model => model.pessoa.cpf)
                </dd>
                <dt class="col-sm-2 menu-listagem">
                    @Html.DisplayNameFor(model => model.pessoa.telefone)
                </dt>
                <dd class="col-sm-10 text-dark menu-listagem">
                    @Html.DisplayFor(model => model.pessoa.telefone)
                </dd>
                <dt class="col-sm-2 menu-listagem">
                    @Html.DisplayNameFor(model => model.pessoa.email)
                </dt>
                <dd class="col-sm-10 text-dark menu-listagem">
                    @Html.DisplayFor(model => model.pessoa.email)
                </dd>
            </div>
            <div class="col">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.pessoa.dataNascimento)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.pessoa.dataNascimento)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.pessoa.naturalidade)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.pessoa.naturalidade)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.pessoa.sexo)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.pessoa.sexo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.pessoa.perfil)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.pessoa.perfil)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.pessoa.createdOn)
                </dt>
                <dd class="col-sm-10 text-dark">
                    @Html.DisplayFor(model => model.pessoa.createdOn)
                </dd>
            </div>
        </div>
    </dl>
</div>
<div class="mt-5">
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.id" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Editar">
        <img width="30" height="30" src="~/img/editar.png">
    </a>
    <a class="btn btn-dark" asp-action="Index" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Voltar para lista">
        <img width="30" height="30" src="~/img/back.png" />
    </a>
</div>

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Pacientes/Edit.cshtml
@using SistemaHospitalar.Domain.Enum
@model SistemaHospitalar.Domain.DTO.PacienteDTO

@{
    ViewData["Title"] = "Editar";
}

<div class="text-center title-page">
    <h1 class="display-1 fw-bold text-success mt-5 mb-5"><strong>Editar Paciente</strong></h1>
</div>                      


<form asp-controller="Pacientes" asp-action="Edit" method="post">
 <div class="container">
    <div class="row justify-content-center">
    <div class="col-3">
        <div class="form-group">
        <input asp-for="id" type="hidden" class="form-control" aria-describedby="emailHelp">
        <input asp-for="pessoaId" type="hidden" class="form-control" aria-describedby="emailHelp">
    </div>

    <div class="form-group">
    <label asp-for="convenioId" for="convenioId" class="color-label">Nome do Convênio</label>
    <select asp-for="convenioId" class="form-control" asp-items="ViewBag.convenioId"></select>
    <span asp-validation-for="convenioId" class="text-danger"></span>  
    </div>

    <div class="form-group mt-2 ">
        <label asp-for="situacao" class="control-label login-title"></label>
        <select asp-for="situacao" class="form-control">
            <option value="0">Selecione</option>
            <option value="@SituacaoEnum.Obito">Óbito</option>
            <option value="@SituacaoEnum.Alta">Alta</option>
            <option value="@SituacaoEnum.Ativo">Ativo</option>
        </select>
        <span asp-validation-for="situacao" class="text-danger"></span>
    </div>
        <div class="buttons-edit-create form-group mt-3 d-flex">
            <input type="submit" class="btn btn-warning btn-sm float-start btn-block w-100" id="button-editar" value="Salvar">
            <a onclick="editPessoa(`../../Pessoas/Edit/@Model.pessoaId`)" class="btn btn-sm btn-primary ms-2 float-end btn-bloc w-100" data-bs-toggle="modal" data-bs-target="#formModal">Editar Dados Pessoais</a>
            
         </div> 
         <a class="btn btn-dark float-none btn-bloc w-100 mt-3" asp-action="Index">Voltar para Lista</a>
</div>

    </div>
 </div>
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
              
    }

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Pacientes/Index.cshtml
@model IEnumerable<SistemaHospitalar.Domain.DTO.PacienteDTO>

@if (TempData["MensagemSucesso"] != null)
{
            <div class="alert alert-success alert-dismissible" role="alert">
               <div> @TempData["MensagemSucesso"]</div>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
}

@if (TempData["MensagemErro"] != null)
{
        <div class="alert alert-danger d-flex align-items-center" role="alert">
        @TempData["MensagemErro"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
}
<h1 class="display-4 mt-5 text-center">Listagem de Pacientes</h1>

<p>
    <a  class="btn btn-primary mt-5" asp-action="Create">Cadastrar Paciente</a>
</p>

<div class="index table-responsive">
<table class="table table-striped table-hover table-sm table-dark" id="table-index">
    <thead>
        <tr class="">
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pessoa.nome)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.pessoa.cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pessoa.rg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.convenio.nome)
            </th>
            <th>
                   Endereços
            </th>
            <th>
                @Html.DisplayNameFor(model => model.situacao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.pessoa.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.pessoa.cpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.pessoa.rg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.convenio.nome)
                </td>
                <td>

                    <a href="#" class="btn btn-success btn-sm" onclick="EnderecoIndex(@item.pessoaId)" data-bs-toggle="modal" data-bs-target="#addressModal">
                        @(@item.pessoa.enderecos != null && @item.pessoa.enderecos.Any() ? @item.pessoa.enderecos.Count() : 0)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.situacao)
                </td>
                <td>
                        <a class="btn btn-outline-primary btn-sm"  asp-action="Edit" asp-route-id="@item.id" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Editar">Editar</a> 
                        <a class="btn btn-outline-warning btn-sm" asp-action="Details" asp-route-id="@item.id" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Ver Detalhes">Detalhes</a>
                        <a class="btn btn-outline-danger btn-sm" href="#" onclick="deleteRegistro(@item.id, 'Paciente', '/Pacientes/Delete')" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Excluir">Excluir </a>
                    </td>
            </tr>
        }
    </tbody>
</table>
</div>


@section Scripts {
    <script>
            const carregaProntuario = (idParam) =>{
                var idPaciente = idParam;
                console.log('oi');
                    $('#modal-body').html();
                    $.ajax({
                        url: '../Prontuarios/Create',
                        dataType: 'html',
                        success: (response) =>{
                            $('#modal-body').html(response)
                        }
                    });
            };

            //const addPessoa = () =>{
            //        $.ajax({
            //            url: '../Pessoas/Create',
            //            dataType: 'html',
            //            success: (response) =>{
            //                $('#modal-body').html(response)
            //            }
            //        });
            //};

            const createProntuario = () =>{
            console.log("oi");
                var prontuario = {
                //pacienteId = idPaciente,
                queixaPrincipal: $('#queixaPrincipal').val(),
                descricao: $('#descricao').val(),
                historicoFamiliar: $('#historicoFamiliar').val(),
                exameFisico: $('#exameFisico').val(),
                condutas: $('#condutas').val(),
                hipoteseDiagnostica: $('#hipoteseDiagnostica').val(),
                prescricao: $('#prescricao').val()
            };

            console.log(prontuario);

            //$.ajax({
            //        url: `../Prontuarios/Create`,
            //        method: 'POST',
            //        data: {
            //            prontuario: prontuario
            //        },
            //        success: (resp) => {
            //            if(resp.code == '200') {
            //                $('#formModal').modal('hide');
            //                liveToastMessage(`O Prontuário foi adicionado.`, 'Prontuário');
            //                setTimeout(()=>{window.location.reload();},4000);
            //            }
            //        }
            //    });


        };

    </script>
}