SlnSistemaHospitalar/src/SistemaHospitalar.Web/Controllers/EspecialidadesController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaHospitalar.Domain.DTO;
using SistemaHospitalar.Domain.IServices;
using SistemaHospitalar.Web.Models;

namespace SistemaHospitalar.Web.Controllers
{
    public class EspecialidadesController : Controller
    {
        private readonly IEspecialidadeMedicaService _service;

        public EspecialidadesController(IEspecialidadeMedicaService service)
        {
            _service = service;
        }


        // GET: EspecialidadesController
        public async Task<IActionResult> Index()
        {
            var conv = await _service.GetAll();
            return View(conv);
        }

        // GET: EspecialidadesController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var esp = await _service.FindById(id);
            return View(esp);
        }

        // GET: EspecialidadesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EspecialidadesController/Create
        [HttpPost]
        public async Task<ActionResult> Create(EspecialidadeMedicaDTO especialidade)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.Save(especialidade);
                    TempData["MensagemSucesso"] = "Especialidade adicionada com sucesso";
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["MensagemErro"] = "Erro ao adicionar especialidade";
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var esp = await _service.FindById(id);
            return View(esp);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EspecialidadeMedicaDTO especialidade)
        {
            if (id == null || especialidade == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _service.Save(especialidade);
                TempData["MensagemSucesso"] = "Especialidade alterada com sucesso";
                return RedirectToAction(nameof(Index));
            }

            TempData["MensagemErro"] = "Erro ao alterar especialidade";
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJson
            {
                status = "Success",
                code = "200"
            };
            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJson
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJson
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Especialidades/Create.cshtml
@model SistemaHospitalar.Domain.DTO.EspecialidadeMedicaDTO

@{
    ViewData["Title"] = "Criar";
}

<div class="text-center title-page">
    <h1 class="display-1 text-success fw-bold mt-5 mb-5"><strong>Adicionar Especialidade Médica</strong></h1>
</div>                      



<form asp-controller="Especialidades" asp-action="Create" method="post">
 <div class="container">
    <div class="row justify-content-center">
    <div class="col-3">
        <div class="form-group text-dark">
         <label asp-for="nome" for="nome" class="color-label">Especialidade:</label>
        <input asp-for="nome" type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Informe a especialidade">
        <span asp-validation-for="nome" class="text-danger"></span>  
    </div>
            <div class="form-group mt-3">
                <input type="submit" value="Cadastrar" class="btn btn-primary btn-block w-100" />
                <a class="btn btn-dark btn-block w-100 mt-3" asp-action="Index">Back to List</a>
            </div>
         </div>
    
    </div>
 </div> 
                                   
</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Especialidades/Edit.cshtml
@model SistemaHospitalar.Domain.DTO.EspecialidadeMedicaDTO

@{
    ViewData["Title"] = "Editar";
}

<div class="text-center title-page">
    <h1 class="display-1 fw-bold text-success mt-5 mb-5"><strong>Editar Especialidade Médica</strong></h1>
</div>                      



<form asp-controller="Especialidades" asp-action="Edit" method="post">
 <div class="container">
    <div class="row justify-content-center">
    <div class="col-3">
        <div class="form-group">
         <label asp-for="nome" for="nome" class="color-label">Especialidade:</label>
        <input asp-for="nome" type="text" class="form-control" aria-describedby="emailHelp" placeholder="Informe a especialidade">
        <span asp-validation-for="nome" class="text-danger"></span>    
    </div>
        <div class="buttons-edit-create form-group mt-3">
            <input type="submit" class="btn btn-warning w-100 btn-block" id="button-editar" value="Editar">
            <a class="btn btn-dark btn-block w-100 mt-3" asp-action="Index">Back to List</a> 
        </div> 
</div>

    </div>
 </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Especialidades/Index.cshtml
@model IEnumerable<SistemaHospitalar.Domain.DTO.EspecialidadeMedicaDTO>

@if (TempData["MensagemSucesso"] != null)
{
            <div class="alert alert-success alert-dismissible" role="alert">
               <div> @TempData["MensagemSucesso"]</div>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
}

@if (TempData["MensagemErro"] != null)
{
        <div class="alert alert-danger d-flex align-items-center" role="alert">
        @TempData["MensagemErro"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
}

<h1 class="display-4 mt-5 text-center">Especialidade Médica</h1>

<p>
    <a class="btn btn-primary mt-5" asp-action="Create">Cadastrar Especialidade</a>
</p>

<div class="index table-responsive">
<table class="table table-striped table-hover table-sm table-dark" id="table-index">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.id" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Editar">
                        <img  width="30" height="30" src="~/img/editar.png">
                    </a>
                        <a class="btn btn-danger" href="#" onclick="deleteRegistro(@item.id, 'Especialidade', '/Especialidades/Delete')" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="Excluir">
                        <img width="30" height="30" src="~/img/lixeira.png">
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>