SlnSistemaHospitalar/src/SistemaHospitalar.Web/Controllers/ConveniosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaHospitalar.Domain.DTO;
using SistemaHospitalar.Domain.IServices;
using SistemaHospitalar.Infra.Data.Context;
using SistemaHospitalar.Web.Models;

namespace SistemaHospitalar.Web.Controllers
{
    public class ConveniosController : Controller
    {
        private readonly IConvenioService _service;

        public ConveniosController(IConvenioService service)
        {
            _service = service;
        }


        // GET: ConveniosController
        public async Task<IActionResult> Index()
        {
            var conv = await _service.GetAll();
            return View(conv);
        }

        // GET: ConveniosController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var conv = await _service.FindById(id);
            return View(conv);
        }

        // GET: ConveniosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ConveniosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ConvenioDTO convenio)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.Save(convenio);
                    TempData["MensagemSucesso"] = "Convênio adicionado com sucesso";
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["MensagemErro"] = "Erro ao adicionar convênio";
                return View();
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var conv = await _service.FindById(id);
            return View(conv);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ConvenioDTO convenio)
        {
            if(id == null || convenio == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _service.Save(convenio);
                TempData["MensagemSucesso"] = "Convênio alterado com sucesso";
                return RedirectToAction(nameof(Index));
            }

            TempData["MensagemErro"] = "Erro ao alterar convênio";
            return RedirectToAction(nameof(Index));
    
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJson
            {
                status = "Success",
                code = "200"
            };
            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJson
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJson
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Controllers/EnderecosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaHospitalar.Domain.DTO;
using SistemaHospitalar.Domain.Entities;
using SistemaHospitalar.Domain.IServices;
using SistemaHospitalar.Web.Models;

namespace SistemaHospitalar.Web.Controllers
{
    public class EnderecosController : Controller
    {
        private readonly IEnderecoService _service;
        private readonly IPacienteService _pacienteService;
        private readonly IPessoaService _pessoaService;

        public EnderecosController(IEnderecoService service, IPacienteService pacienteService, IPessoaService pessoaService)
        {
            _service = service;
            _pessoaService = pessoaService;
            _pacienteService = pacienteService;

        }


        // GET: EnderecosController
        public async Task<ActionResult> Index()
        {
            var Endereco = await _service.GetAll();
            return View(Endereco);
        }

        public async Task<PartialViewResult> ListaEndereco(int id)
        {
            var lista = await _service.ListaEndereco(id);
            //var lista = await _service.GetAll();
            return PartialView(lista);
        }

        // GET: EnderecosController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var endereco = await _service.FindById(id);
            return View(endereco);
        }

        // GET: EnderecosController/Create
        public PartialViewResult Create()
        {
            return PartialView();
        }

        // POST: EnderecosController/Create
        [HttpPost]

        public async Task<JsonResult> Create(EnderecoDTO endereco)
        {
            

            var retDel = new ReturnJson
            {
                status = "Error",
                code = "400"
            };

            //if(id = 0){


            var pessoas = await _pessoaService.GetAll();

            int count = 0;
            foreach (var item in pessoas)
            {
                count++;
                if (count == pessoas.Count)
                {
                    //ultima Pessoa
                    endereco.pessoaId = item.id;
                }
            }

            if (ModelState.IsValid)
            {

                await _service.Save(endereco);
                TempData["MensagemSucesso"] = "Endereço adicionado com sucesso";
                retDel = new ReturnJson
                {
                    status = "Success",
                    code = "200"
                };
            };
            return Json(retDel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endereco = await _service.FindById(id);

            return View(endereco);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EnderecoDTO endereco)
        {
            if (id == null || endereco == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.Save(endereco);
                TempData["MensagemSucesso"] = "Registro alterado com sucesso";
                return RedirectToAction(nameof(Index));
            }

            TempData["MensagemErro"] = "Erro ao alterar registro";
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJson
            {
                status = "Success",
                code = "200"
            };
            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJson
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJson
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Controllers/MedicosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaHospitalar.Domain.DTO;
using SistemaHospitalar.Domain.Entities;
using SistemaHospitalar.Domain.IServices;
using SistemaHospitalar.Web.Models;

namespace SistemaHospitalar.Web.Controllers
{
    public class MedicosController : Controller
    {
        private readonly IMedicoService _service;
        private readonly IPessoaService _pessoaService;
        private readonly IEspecialidadeMedicaService _especialidadeService;

        public MedicosController(IMedicoService service, IPessoaService pessoaService, IEspecialidadeMedicaService especialidadeService)
        {
            _service = service;
            _pessoaService = pessoaService;
            _especialidadeService = especialidadeService;
        }


        // GET: MedicosController
        public async Task<IActionResult> Index()
        {
            var medico = await _service.GetAll();
            return View(medico);
        }

        // GET: MedicosController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medico = await _service.FindById(id);
            return View(medico);
        }

        // GET: MedicosController/Create
        public async Task<ActionResult> Create()
        {
            ViewData["especialidadeId"] = new SelectList(await _especialidadeService.GetAll(), "id", "nome", "Selecione...");
            return View();
        }

        // POST: MedicosController/Create
        [HttpPost]

        public async Task<IActionResult> Create(MedicoDTO medico)
        {
            var pessoas = await _pessoaService.GetAll();

            int count = 0;
            foreach (var item in pessoas)
            {
                count++;
                if (count == pessoas.Count)
                {
                    //ultima Pessoa
                    medico.pessoaId = item.id;
                }
            }
            
            if (ModelState.IsValid)
            {

                await _service.Save(medico);
                TempData["MensagemSucesso"] = "Médico adicionado com sucesso";
                return RedirectToAction(nameof(Index));
            }
            ViewData["especialidadeId"] = new SelectList(await _especialidadeService.GetAll(), "id", "nome", "Selecione...");
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medico = await _service.FindById(id);
            ViewData["especialidadeId"] = new SelectList(await _especialidadeService.GetAll(), "id", "nome", "Selecione...");
            return View(medico);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, MedicoDTO medico)
        {
            if (id == null || medico == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.Save(medico);
                TempData["MensagemSucesso"] = "Registro alterado com sucesso";
                return RedirectToAction(nameof(Index));
            }

            TempData["MensagemErro"] = "Erro ao alterar registro";
            return RedirectToAction(nameof(Index));

        }


        // POST: MedicosController/Delete/5
        [HttpPost]
        public async Task<JsonResult> Delete(int? id)
        {
            var retDel = new ReturnJson
            {
                status = "Success",
                code = "200"
            };
            try
            {
                if (await _service.Delete(id ?? 0) <= 0)
                {
                    retDel = new ReturnJson
                    {
                        status = "Error",
                        code = "400"
                    };
                }
            }
            catch (Exception ex)
            {
                retDel = new ReturnJson
                {
                    status = ex.Message,
                    code = "500"
                };
            }
            return Json(retDel);
        }
    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Controllers/PessoasController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaHospitalar.Domain.DTO;
using SistemaHospitalar.Domain.IServices;
using SistemaHospitalar.Web.Models;
using SistemaHospitalar.Domain.Entities;

namespace SistemaHospitalar.Web.Controllers
{
    public class PessoasController : Controller
    {
        private readonly IPessoaService _service;

        public PessoasController(IPessoaService service)
        {
            _service = service;
        }


        // GET: PessoasController
        public async Task<IActionResult> Index()
        {
            var pessoa = await _service.GetAll();
            return View(pessoa);
        }

        // GET: PessoasController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _service.FindById(id);
            return View(pessoa);
        }

        // GET: PessoasController/Create
        public PartialViewResult Create()
        {
            return PartialView();
        }

        // POST: PessoasController/Create
        [HttpPost]
        public async Task<IActionResult> Create(PessoaDTO pessoa)
        {

            pessoa.createdOn = DateTime.Now;
            var retDel = new ReturnJson
            {
                status = "Error",
                code = "400"
            };
            if (ModelState.IsValid)
            {
                await _service.Save(pessoa);
                retDel = new ReturnJson
                {
                    status = "Success",
                    code = "200"
                };
            }

            return Json(retDel);
        }

        public async Task<PartialViewResult> Edit(int id)
        {

            var pessoa = await _service.FindById(id);
            return PartialView(pessoa);
        }

        [HttpPost]
        public async Task<JsonResult> Edit(int id, PessoaDTO pessoa)
        {
            var retDel = new ReturnJson
            {
                status = "Error",
                code = "400"
            };
            if (ModelState.IsValid)
            {
                await _service.Save(pessoa);
                retDel = new ReturnJson
                {
                    status = "Success",
                    code = "200"
                };
            }

            return Json(retDel);

        }

    }
}

SlnSistemaHospitalar/src/SistemaHospitalar.Web/Views/Shared/Components/Menu/Default.cshtml
@using SistemaHospitalar.Domain.Entities
@using SistemaHospitalar.Domain.Enum;
@model SistemaHospitalar.Domain.DTO.PessoaDTO

<div class="container-fluid position-static">
    <a class="navbar-brand text-white fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Hollywood News</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-link text-white " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="NoticiasVisiveis" asp-action="Index">Notícias</a>
            </li>

            @if (Model.perfil == PerfilEnum.Admin)
            {
                <ul>
                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Convenios" asp-action="Index">Convênio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">Paciente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicos" asp-action="Index">Médicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especialidades" asp-action="Index">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recepcionistas" asp-action="Index">Recepcionistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enderecos" asp-action="Index">Endereços</a>
                        </li>
                    </ul>

            }

            if(Model.perfil == PerfilEnum.Medico){
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">Paciente</a>
                </li>
            }

            if(Model.perfil == PerfilEnum.Recepcionista){
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">Paciente</a>
                </li>
            }


            <li class="nav-item dropdown position-absolute end-0 top-0">
              <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    @Model.nome
                    <img class="me-2 img-menu" src="~/img/user.png" />
              </a>
              <ul class="dropdown-menu">
                <li><a asp-controller="Login" asp-action="Sair" class="dropdown-item">Log Out</a></li>
              </ul>
        </li>
        </ul>
    </div>
</div>